# Generated by Django 6.0.3 on 2026-04-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("welcome_text", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
    ]
