# Generated by Django 6.0.3 on 2026-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_hero"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
            ],
        ),
    ]
