# Generated by Django 6.0.3 on 2026-04-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="Tech", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
    ]
