# Generated by Django 6.0.3 on 2026-04-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("quote", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("stars", models.IntegerField(default=5)),
            ],
        ),
    ]
