# Generated by Django 6.0.3 on 2026-04-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("app", "App"),
                            ("product", "Product"),
                            ("branding", "Branding"),
                            ("books", "Books"),
                        ],
                        default="app",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/")),
                ("link", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
